// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyMM0tRzy95XarreBxKQ-MIDQiYomvrw',
    appId: '1:27427710490:android:6aec878d761fd6c9f2d3a3',
    messagingSenderId: '27427710490',
    projectId: 'notesapp-flutter-82e1a',
    storageBucket: 'notesapp-flutter-82e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwwSuzJy4YrQMdhArZCQ-3jM4ohiqLr0',
    appId: '1:27427710490:ios:2d879a5a8ebc09cef2d3a3',
    messagingSenderId: '27427710490',
    projectId: 'notesapp-flutter-82e1a',
    storageBucket: 'notesapp-flutter-82e1a.appspot.com',
    iosClientId: '27427710490-1ih2v9rh2bf08coih3j2asnlkrm8c90m.apps.googleusercontent.com',
    iosBundleId: 'com.harsh082ip.notesapp.notesApp',
  );
}
